### ISSUE TITLE
Alternatives to using key-pair authentication

### ISSUE THREAD

**Issue by leonheldattoradex** [toradex/torizon-samples#16]
https://github.com/toradex/torizon-samples/pull/15#discussion_r1439390099

**Comment by andreriesco** [comment]
This comes from the [vscode-torizon-templates](https://github.com/toradex/vscode-torizon-templates/issues) repo. Can you open this issue there, please?

**Comment by leonheldattoradex** [comment]
https://github.com/toradex/vscode-torizon-templates/issues/155
