### ISSUE TITLE
Broken link in node.js example

### ISSUE THREAD

**Issue by escherstair** [toradex/torizon-samples#5]
A node.js sample has just been added to the repo.
The README.md refers to the [Node.js on Torizon](https://developer.toradex.com/torizon/application-development/nodejs-on-torizon) article, but the link doesn't exist.

**Comment by leograba** [comment]
Thanks for reporting. The documentation is going through a final round of review and will be available soon.

**Comment by leograba** [comment]
The article has been published, the hyperlink should work now.
